# Generated by Django 6.0.2 on 2026-03-06 09:22

import django.db.models.deletion
import wallet.util
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('account_number', models.CharField(default=wallet.util.get_account_number, max_length=10, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('NGN', 'Naira'), ('USD', 'Dollar'), ('EUR', 'Euro')], default='NGN', max_length=3)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('CANCELED', 'Canceled'), ('FAILED', 'Failed')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(default=wallet.util.generate_reference, max_length=40)),
                ('receiver_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_wallet', to='wallet.wallet')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.wallet')),
            ],
        ),
    ]
