# Generated by Django 6.0.2 on 2026-02-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
    ]
